replicaCount: 5

image:
  repository: mammuthosting/twitch-tracker

imagePullSecrets:
  - name: image-pull-secret

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.frontend.passHostHeader: 'true'
    traefik.ingress.kubernetes.io/router.middlewares: >-
      traefik-api-stripprefix@kubernetescrd,traefik-v1-stripprefix@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
  hosts:
    - host: prod.tracker.twitch.mammut-cluster.de
      paths:
        - path: /api/v1
          pathType: Prefix
  tls:
    - secretName: prod.tracker.twitch.mammut-cluster.de
      hosts:
        - prod.tracker.twitch.mammut-cluster.de

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits: {}

maxUnavailable: 1

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node.kubernetes.io/server-usage
              operator: In
              values:
                - workload

    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node.kubernetes.io/agent-size
              operator: In
              values:
                - xlarge

service:
  type: ClusterIP
  port: 1337

env:
  secretName: twitch-tracker-env

autoscaling:
  enabled: false
