version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - ./docker/redis-insight:/db
    networks:
      network:
        ipv4_address: 10.5.0.254

  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.0
    ports:
      - '6379:6379'
    volumes:
      - ./docker/redis-cluster_data-0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      network:
        ipv4_address: 10.5.0.2
    restart: on-failure
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.0
    ports:
      - '6380:6379'
    volumes:
      - ./docker/redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      network:
        ipv4_address: 10.5.0.3
    restart: on-failure
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.0
    ports:
      - '6381:6379'
    volumes:
      - ./docker/redis-cluster_data-2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      network:
        ipv4_address: 10.5.0.4
    restart: on-failure
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.0
    ports:
      - '6382:6379'
    volumes:
      - ./docker/redis-cluster_data-3:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      network:
        ipv4_address: 10.5.0.5
    restart: on-failure
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.0
    ports:
      - '6383:6379'
    volumes:
      - ./docker/redis-cluster_data-4:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      network:
        ipv4_address: 10.5.0.6
    restart: on-failure
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.0
    ports:
      - '6387:6379'
    volumes:
      - ./docker/redis-cluster_data-5:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'
    networks:
      network:
        ipv4_address: 10.5.0.7
    restart: on-failure
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
