version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - ./docker/redis-insight:/db
    networks:
      network:
        ipv4_address: 10.5.0.254

  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./docker/redis:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
    restart: on-failure
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
