name: Node CI

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/**'
      - 'spec/**'
      - 'prisma/**'
      - 'package.json'
      - 'yarn.lock'
      - '.nvmrc'
      - '.nycrc'
      - '.eslintignore'
      - '.eslintrc.js'

  workflow_dispatch:

jobs:
  check-ci:
    name: Node Engine Check
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --non-interactive --no-progress --prefer-offline

      - name: CI Node Engine Check
        run: yarn ci:checkNodeEngine

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --non-interactive --no-progress --prefer-offline

      - name: Check Linting
        run: yarn lint
