name: Release

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --non-interactive --no-progress --prefer-offline

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        run: npx semantic-release
